[build]
  base = "."
  publish = "public"
  command = "npm run build"

[functions]
  directory = "dist/api"

[[redirects]]
  from = "/login-to-web"
  to = "/.netlify/functions/login-to-web"
  status = 200
