[build]
  base = "."
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
  included_files = ["node_modules/@sparticuz/chromium/**/*"]

[[redirects]]
  from = "/login-to-web"
  to = "/.netlify/functions/login-to-web"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/status"
  to = "/.netlify/functions/status"
  status = 200
